
[supervisord]
nodaemon=true


[program:rnsd]
command=/opt/venv/bin/rnsd --service --config /rns-pep
directory=/rns-pep
autostart=true
autorestart=true


[program:lxmd]
command=/opt/venv/bin/lxmd --service --config /rns-pep/lxmd --rnsconfig /rns-pep
directory=/rns-pep
autostart=true
autorestart=true


[program:rns-page-node]
command=/opt/venv/bin/rns-page-node /rns-pep/rns-page-node.conf -c /rns-pep
directory=/rns-pep
autostart=true
autorestart=true
